use_frameworks!

platform :ios, '9.0'

target 'KloverLib_Example' do
  pod 'KloverLib', :path => '../'

  target 'KloverLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
