#ifndef IREAD_DEFINE_H
#define IREAD_DEFINE_H
#define REGISTERED_TAG_NUMBER 500

enum eErrorMsg
{
    eERR_SUCCESS = 0,
    eERR_FOCUS_BLUR = 1,
    eERR_BRIGHT_UNDER_BEFORE_FINDEDGE = 2,
    eERR_BRIGHT_OVER_BEFORE_FINDEDGE = 3,
    eERR_NOT_EXIST_CONTOUR = 4,
    eERR_CALCULATE_EDGE_LINE = 5,
    eERR_CONTOUR_SIZE_ERROR = 6,
    eERR_PERSPECTIVE_TRANSFORM_MAT = 7,
    eERR_PERSPECTIVE_TRANSFORM_APPLY = 8,
    eERR_TRILLCODE_ERROR = 9,
    eERR_NOT_RGB_COLOR = 10,
    eERR_BRIGHT_UNDER_AFTER_FINDEDGE = 11,
    eERR_BRIGHT_OVER_AFTER_FINDEDGE = 12,
	eERR_HIDDENCODE_ERROR = 13,
    eERR_NOT_GENUINE_OVER_SIZE = 14,
    eERR_COPY_LINE_PROFILE = 15,
    eERR_COPY_K10 = 16,
    eERR_LESS_SUCCESS = 17,
    eERR_ASSUME_NOT_GENUINE = 18,
    eERR_TRILLCODE_DIRECTION = 19,
    eERR_TOUR_TRILLCODE_SUCCESS = 20,
    eERR_TRILLCODE_INVALID = 21,
    eERR_FIND_CIRCLE_SUCCESS = 98,
    eERR_FIND_EDGE_SUCCESS = 99,
    eERR_UNKNOWN = 100,
    eERR_NOT_GENUINE2 = 130,
    eERR_NOT_GENUINE3 = 131,
    eERR_NOT_GENUINE4 = 132
};

enum ePhone
{
    e_IPHONE6 = 0,
    e_IPHONE7 = 1,
    e_LG = 2,
    e_SAMSUNG = 3,
    e_ELSE = 4
};

#define TAG_TYPE_IMAGE 0
#define TAG_TYPE_QR 1
#define TAG_SHAPE_SQUARE 0
#define TAG_SHAPE_RECTANGLE 1
#define TAG_SHAPE_CIRCLE 2
#define TAG_SHAPE_MOUTAI 3

#define HIDDEN_CODE_COUNT 3
#define HIDDEN_CODE_1 0
#define HIDDEN_CODE_2 1
#define HIDDEN_CODE_3 2

#define HIDDEN_VALUE_COUNT 4

#define TAG_WIDTH_720 720
#define TAG_HEIGHT_720 720
#define TAG_WIDTH_998 998
#define TAG_HEIGHT_434 434

#define HIDDEN_CODE_LENGTH_30 30
#define HIDDEN_CODE_LENGTH_22 22
#define HIDDEN_CODE_LENGTH_18 18

#define EDGE_POINT_OFFSET 5
#define EDGE_POINT_THRESHOLD 100

#define EDGE_CHANGE_THRESHOLD_IMAGETAG 2
#define EDGE_CHANGE_THRESHOLD_QRTAG 2

#define MIN_TAG_AREA_RATIO_0_35 0.35
#define MIN_TAG_AREA_RATIO_0_40 0.40
#define MIN_TAG_AREA_RATIO_0_45 0.45

#define FOCUS_THRESHOLD 100
#define FOCUS_THRESHOLD_IPHONE_6 1000
#define FOCUS_THRESHOLD_IPHONE_7 1250
#define FOCUS_THRESHOLD_OTHERS 100
#define FOCUS_THRESHOLD_LG 30

#define HISTOGRAM_THRESHOLD_UNDER 80
#define HISTOGRAM_THRESHOLD_OVER 230

#define BW_PAIR_COUNT_HOR 2
#define BW_PAIR_COUNT_VER 8
#define HISTOGRAM_MATCHING_RATIO 0.97

#define BLACK_THRESHOLD 50
#define WHITE_THRESHOLD 200

#define GENUINE_TRUEFALSE_THRESHOLD 4

#define PIXEL_COUNT_RATIO_LARGE 0.75
#define PIXEL_COUNT_RATIO_MIN 0.5
#define PIXEL_COUNT_RATIO_MEDIUM 0.6
#define PIXEL_COUNT_RATIO_MAX 0.7

#define BLACK_LINE_COUNT_MIN 2
#define BLACK_LINE_COUNT_MAX 4

#define CROSS_CHECK_OFFSET_LARGE 5

#define TRILL_HEIGHT_16 16
#define TRILL_WIDTH_100 100
#define TRILL_WIDTH_300 300
#define TRILL_WIDTH_500 500

#define TRILL_READ_OFFSET 3

#define TRILL_BLACK_THRESHOLD 120
#define TRILL_WHITE_THRESHOLD 150

#define TRILL_CODE_BREAK 3
#define TRILL_MAX_ZERORUN 5

#define TRILL_COMPANY_LENGTH_DECIMAL 4
#define TRILL_BRAND_LENGTH_DECIMAL 2
#define TRILL_PRODUCT_LENGTH_DECIMAL 2

#define TRILL_COMPANY_LENGTH_BINARY 10
#define TRILL_BRAND_LENGTH_BINARY 4
#define TRILL_PRODUCT_LENGTH_BINARY 4

#define TRILL_CODE_RESOURCE_LENGTH 46
#define QR_CODE_URL_STRING_LENGTH 128
#define TOTAL_RESOURCE_LENGTH 65

#define TRILL_CODE_LENGTH_PER_SQUARE 12
#define TRILL_CODE_LENGTH_PER_RECTANGLE 21
#define TRILL_MIN_LENGTH_PER_UNIT 5
#define TRILL_CODE_IMAGE_UNIT_LENGTH 100

#define BIT_0 0
#define BIT_1 1
#define BIT_2 2
#define BIT_3 3
#define BIT_4 4
#define BIT_5 5
#define BIT_6 6
#define BIT_7 7
#define BIT_8 8
#define BIT_9 9
#define BIT_10 10
#define BIT_11 11
#define BIT_12 12
#define BIT_13 13
#define BIT_14 14
#define BIT_15 15
#define BIT_16 16
#define BIT_17 17
#define BIT_18 18
#define BIT_19 19
#define BIT_20 20
#define BIT_21 21
#define BIT_22 22
#define BIT_23 23
#define BIT_24 24
#define BIT_25 25
#define BIT_26 26
#define BIT_27 27
#define BIT_28 28
#define BIT_29 29
#define BIT_30 30
#define BIT_31 31
#define BIT_32 32
#define BIT_33 33
#define BIT_34 34
#define BIT_35 35
#define BIT_36 36
#define BIT_37 37
#define BIT_38 38
#define BIT_39 39
#define BIT_40 40

#define TRILL_CODE_CELL_WIDTH 17
#define TRILL_CODE_CELL_HEIGHT 17
#define TRILL_CODE_CELL_OFFSET 5
#define TRILL_CODE_CELL_REFVALUE_GAP 5

#define TRILL_CODE_WIDTH2 347
#define TRILL_CODE_HEIGHT2 17
#define TRILL_CODE_WIDTH2_FIX 340
#define TRILL_CODE_CELL_COUNT 20
#define TRILL_CODE_CELL_COUNT_SQUARE TRILL_CODE_LENGTH_PER_SQUARE + 3

#define TRILL_CODE_WIDTH3 486
#define TRILL_CODE_HEIGHT3 17
#define TRILL_CODE_WIDTH3_FIX 476
#define TRILL_CODE_CELL_COUNT2 28
#define TRILL_CODE_CELL_COUNT_RECTANGLE TRILL_CODE_LENGTH_PER_RECTANGLE + 3

#define TRILL_CODE_SQUARE_UP_BIT_START 1
#define TRILL_CODE_SQUARE_UP_BIT_COMPANY 9
#define TRILL_CODE_SQUARE_UP_BIT_PARITY 1
#define TRILL_CODE_SQUARE_UP_BIT_END 1
#define TRILL_CODE_SQUARE_UP_DATA_LENGTH TRILL_CODE_SQUARE_UP_BIT_START + TRILL_CODE_SQUARE_UP_BIT_COMPANY + TRILL_CODE_SQUARE_UP_BIT_PARITY + TRILL_CODE_SQUARE_UP_BIT_END

#define TRILL_CODE_SQUARE_LEFT_BIT_START 1
#define TRILL_CODE_SQUARE_LEFT_BIT_COMPANY 1
#define TRILL_CODE_SQUARE_LEFT_BIT_BRAND 4
#define TRILL_CODE_SQUARE_LEFT_BIT_PRODUCT 4
#define TRILL_CODE_SQUARE_LEFT_BIT_PARITY 1
#define TRILL_CODE_SQUARE_LEFT_BIT_END 1
#define TRILL_CODE_SQUARE_LEFT_DATA_LENGTH TRILL_CODE_SQUARE_LEFT_BIT_START + TRILL_CODE_SQUARE_LEFT_BIT_COMPANY + TRILL_CODE_SQUARE_LEFT_BIT_BRAND + TRILL_CODE_SQUARE_LEFT_BIT_PRODUCT + TRILL_CODE_SQUARE_LEFT_BIT_PARITY + TRILL_CODE_SQUARE_LEFT_BIT_END

#define TRILL_CODE_RECTANGLE_UP_BIT_START 1
#define TRILL_CODE_RECTANGLE_UP_BIT_COMPANY 10
#define TRILL_CODE_RECTANGLE_UP_BIT_BRAND 4
#define TRILL_CODE_RECTANGLE_UP_BIT_PRODUCT 4
#define TRILL_CODE_RECTANGLE_UP_BIT_PARITY 1
#define TRILL_CODE_RECTANGLE_UP_BIT_END 1
#define TRILL_CODE_RECTANGLE_UP_DATA_LENGTH TRILL_CODE_RECTANGLE_UP_BIT_START + TRILL_CODE_RECTANGLE_UP_BIT_COMPANY + TRILL_CODE_RECTANGLE_UP_BIT_BRAND + TRILL_CODE_RECTANGLE_UP_BIT_PRODUCT + TRILL_CODE_RECTANGLE_UP_BIT_PARITY + TRILL_CODE_RECTANGLE_UP_BIT_END

#define OFFSET_CHECK_LINE_PROFILE_X 5
#define OFFSET_CHECK_LINE_PROFILE_Y 5
#define OFFSET_QR_CHECK_COPY_WIDTH 160
#define OFFSET_CHECK_LINE_PROFILE_HEIGHT 8
#define LINE_PROFILE_THRESHOLD_IOS 10
#define LINE_PROFILE_THRESHOLD_ANDROID 10.00
#define PIXEL_MATCHING_THRESHOLD_IMAGE 0.7f
#define PIXEL_MATCHING_THRESHOLD_QR 0.6f

#define OFFSET_QR_EDGE_CAMERA1 40
#define OFFSET_QR_EDGE_CAMERA2 70

#define TAG_WIDTH_720_GAP 30
#define TAG_HEIGHT_720_GAP 30

#define TAG_WIDTH_720_ANALYZE_X 495
#define TAG_HEIGHT_720_ANALYZE_Y 500
#define TAG_WIDTH_720_ANALYZE_WIDTH 195
#define TAG_HEIGHT_720_ANALYZE_HEIGHT 140

#define GOOD_MATCH_DIST_LEVEL 50
#define GOOD_MATCH_DIST_LEVEL2 25
#define GOOD_MATCH_DECISION_ALL 300
#define GOOD_MATCH_ANALYZE_AREA_ALL 0
#define GOOD_MATCH_ANALYZE_AREA_SOME 1

#define GOOD_MATCH_IMAGE_NUM_DECIMAL 3
#define GOOD_MATCH_CUTOFF_DECIMAL 4
#define GOOD_MATCH_IMAGE_NUM_DECIMAL_IPHONE 3
#define GOOD_MATCH_CUTOFF_DECIMAL_IPHONE 4

#define OCR_DISP_OFF_FLAG 1

#define GOOD_MATCH_LEVEL 3

#define RETURN_ALWAYS_GENUINE_FLAG 1

#define GOOD_MATCH_IMAGE_NUM_DECIMAL2 3
#define GOOD_MATCH_CUTOFF_DECIMAL2 4
#define GOOD_MATCH_IMAGE_NUM_DECIMAL2_IPHONE 3
#define GOOD_MATCH_CUTOFF_DECIMAL2_IPHONE 4
#define GOOD_MATCH_X 3
#define GOOD_MATCH_Y 3
#define GOOD_MATCH_WIDTH 3
#define GOOD_MATCH_HEIGHT 3
#define GOOD_MATCH_LEVEL2 3

#endif
